### ISSUE TITLE
How to use Co-dfns in Dyalog; no .dws file?

### ISSUE THREAD

**Issue by tlack** [arcfide/Co-dfns#257]
Potentially stupid question as I am new to Dyalog, APL, and of course Co-dfns. 

I notice that your wiki refers to opening the workspace file (.dws) to use Co-dfns, but I don't see that provided in the git repo. How do I generate this workspace file, or import Co-dfns without the workspace?

If it matters, I am using Dyalog unregistered version 14.0.

**Comment by arcfide** [comment]
Thank you for your inquiry! I'm happy to help you out on this. The first thing you should be aware of is that Co-dfns is currently changing rapidly, so it's best to stay in close contact with me as you work with the compiler. Secondly, I've removed the dependency on the workspace recently, so that you can use the SALT system to do all of your configuration. 

Are you on Windows, Mac, or Linux? If you would like, I can get on a conference call and help you get things configured. The basic steps are as follows:

1. Copying config.dyalog.template to config.dyalog and use this to set your personalized settings for the compiler, including what your back-end compiler will be, the compilers you want to use to run the test suite, and where you find the compilers if you are on Windows. If you are on Linux and using GCC, here is what you would use in your config.dyalog file:

    #.codfns.COMPILER←'gcc'
    #.codfns.TEST∆COMPILERS←⊂'gcc'

If you are on Windows you need to make sure that you also set up the right paths to point you to the particular installation of Visual Studio or PGI that you have: Here are the set of compiler configuration variables as they come by default:

    VERSION	←0 4 42 ⋄ COMPILER←'vsc'
    DWA∆PATH	←'dwa'
    BUILD∆PATH	←'Build'
    TEST∆COMPILERS	←⊂'vsc'
    VISUAL∆STUDIO∆PATH	←'C:\Program Files (x86)\Microsoft Visual Studio 14.0\'
    INTEL∆C∆PATH	←'C:\Program Files (x86)\IntelSWTools\'
    INTEL∆C∆PATH	,←'compilers_and_libraries_2016.0.110\windows\bin\'
    PGI∆PATH	←'C:\Program Files\PGI\win64\15.7\'

Once you have setup config.dyalog the way you want, you will see the load.dyapp file in the repository:

    Target #
    Load util
    Load codfns
    Load APLUnit\UT
    Load config

This file has all of the Load commands to get you into a Co-dfns development environment, where you can test and use the compiler. On Windows you should be able to just double click on that load.dyapp file once you have set up your config.dyalog settings. There is also a test.dyapp file that will automatically run the test suite. If you are on Linux, I use the following command to load up the Co-dfns environment:

    $ dyapp=./load.dyapp mapl

Right now the Co-dfns compiler is undergoing rapid evolution as I am at this moment working on bitvector support and the like for some benchmarks. I'm happy to talk with you further to make sure you get things running to your satisfaction, just let me know. Current master branch will be a little unstable, so if you encounter some issues, I can point you to the best checkout to use right now.

**Comment by arcfide** [comment]
I forgot to mention in the above, but you need to make sure that you have two directories available to you in order to use Co-dfns. You need a Build directory to story your build artifacts from the compiler, and you need to have a copy of dwa put in a place where Co-dfns can find it. That is what the `DWA∆PATH` and `BUILD∆PATH` variables are for. The other path variables are for your Windows compilers, and you need to set them to the right path for whatever compiler you want to use.

**Comment by tlack** [comment]
Thanks! I'm installing Visual Studio and I'll let you know how it goes. 

As an aside, I found the Co-dfns code pretty tight and readable, despite not knowing much APL. So kudos on your great work!

I am very curious to see how your system manages the runtime state in the compiled program, since it seems that APL is much more dynamic than C. I have been pondering vector language implementations for some time now, even more so after Kx recently un-freed Q.

**Comment by arcfide** [comment]
I'd recommend that if you want to read the source code of Co-dfns, it's important for you to use Code-Brwoser as an editor or any other editor that supports its style of code folding. It makes the organization of the file much better.

**Comment by arcfide** [comment]
Here is the website to code-browser: http://tibleiz.net/code-browser/

**Comment by arcfide** [comment]
When you install Visual Studio, make sure that the C/C++ compiler is installed as a part of that.

**Comment by arcfide** [comment]
Let me know if you need more help. I am going to consider this issue closed. Please open up another one if you are having a new problem. :-)
